# -*- coding: utf-8 -*-
"""02 - White-label / OEM agreement, supplement to the reseller framework agreement.

THE ONE HONEST CONSTRAINT IN HERE is clause 4. byon can put its own brand on every deliverable,
because the platform supports it: a partner uploads its own PowerPoint template and the palette,
fonts and logo are read out of it and applied to every deck and report that partner generates
afterwards. What byon cannot do unilaterally is remove the attribution line, because that is
controlled by the Distribution Agreement between objectale and the operator. Saying so in the contract is
better than discovering it on the first customer deck.
"""
from common import BYON, DATE_DE, DATE_EN, NOTE_DE, NOTE_EN, OBJECTALE, OPERATOR, PLATFORM, VERSION

EN = [
    ("h1", "WHITE-LABEL / OEM AGREEMENT"),
    ("meta", "%s and %s  ·  Supplement to the Reseller Framework Agreement  ·  Version %s  ·  %s"
     % (OBJECTALE["name"], BYON["name"], VERSION, DATE_EN)),
    ("p", "This White-Label / OEM Agreement (this \"OEM Agreement\") takes effect on [OEM effective "
          "date] between %s (\"objectale\") and %s (\"byon\")."
     % (OBJECTALE["name"], BYON["name"])),
    ("note", NOTE_EN),

    ("h2", "1. Relationship to the Reseller Framework Agreement"),
    ("num", "1.1", "This OEM Agreement supplements the Reseller Framework Agreement between the "
                   "parties dated [date of the framework agreement] (the \"Framework Agreement\") "
                   "and forms part of it."),
    ("num", "1.2", "Terms defined in the Framework Agreement have the same meaning here unless "
                   "defined differently in clause 2."),
    ("num", "1.3", "Where this OEM Agreement conflicts with the Framework Agreement, this OEM "
                   "Agreement prevails for white-label matters only."),
    ("num", "1.4", "Nothing here varies clause 15 (Confidentiality), clause 17 (Liability), clause "
                   "24 (Governing law and jurisdiction) or the Data Processing Agreement."),
    ("num", "1.5", "This OEM Agreement ends automatically when the Framework Agreement ends."),

    ("h2", "2. Definitions"),
    ("num", "2.1", "\"Branded Deliverable\" means a deck, report or run log generated by the "
                   "platform and carrying byon's brand under clause 3."),
    ("num", "2.2", "\"Brand Assets\" means the template, logo, colour palette and typeface byon "
                   "supplies for that purpose."),
    ("num", "2.3", "\"Attribution\" means the single line identifying the platform that appears on "
                   "the cover of each deliverable."),
    ("num", "2.4", "\"Tenant\" means byon's separately configured account on the platform."),

    ("h2", "3. Grant of white-label rights"),
    ("num", "3.1", "objectale grants byon a non-exclusive, non-transferable right, for the term "
                   "and in the Territory, to present the platform and its deliverables under "
                   "byon's own brand."),
    ("num", "3.2", "byon may apply its Brand Assets so that every deck and report it generates "
                   "carries byon's colours, fonts and logo. byon applies them itself through the "
                   "platform's white-label function by uploading its own template; objectale does "
                   "not need to be involved in each change."),
    ("num", "3.3", "byon may name the service in its own price list and marketing under a name of "
                   "byon's choosing, provided that name is not confusingly similar to the "
                   "platform's name or to a mark of the Vendor."),
    ("num", "3.4", "byon may present itself to its customers as the contracting party and the "
                   "service provider for the branded service."),
    ("num", "3.5", "The right does not include the source code, the right to host the platform on "
                   "byon's own infrastructure, or the right to modify the assessment engine."),

    ("h2", "4. Limits that come from the chain of rights"),
    ("p", "This clause states plainly what objectale is not able to grant, so that byon does not "
          "promise it to a customer."),
    ("num", "4.1", "The Attribution is controlled by the Distribution Agreement between objectale and the "
                   "Vendor. Unless Schedule A records that the Vendor has agreed to its "
                   "removal for byon, each deliverable carries one small attribution line and byon "
                   "will not remove, obscure or alter it."),
    ("num", "4.2", "Severity colours, and any other element the platform treats as carrying "
                   "meaning for the reader rather than brand identity, are not re-coloured by the "
                   "white-label function and byon will not attempt to change them."),
    ("num", "4.3", "objectale will ask the Vendor, on byon's written request, whether a further "
                   "white-label right can be granted, and will tell byon the answer. objectale "
                   "gives no assurance that the answer will be yes."),
    ("num", "4.4", "Where the Vendor withdraws or narrows a white-label right, objectale will "
                   "notify byon without undue delay and the parties will agree in good faith how "
                   "byon's existing customer commitments are handled."),

    ("h2", "5. Brand assets and quality"),
    ("num", "5.1", "byon grants objectale and the Vendor a licence to use the Brand Assets only "
                   "to render Branded Deliverables for byon. The licence ends when this OEM "
                   "Agreement ends."),
    ("num", "5.2", "byon warrants that it holds the rights in the Brand Assets and that their use "
                   "under this OEM Agreement infringes no third-party right, and indemnifies "
                   "objectale against claims to the contrary."),
    ("num", "5.3", "byon is responsible for reviewing the rendered result before it is sent to a "
                   "customer. The platform shows byon a rendered cover and content slide before a "
                   "brand is saved; byon will use that step."),
    ("num", "5.4", "byon will not present a Branded Deliverable in a way that suggests the "
                   "assessment was produced by a certification body, an auditor or a regulator."),

    ("h2", "6. Tenant set-up and acceptance"),
    ("num", "6.1", "objectale will configure byon's Tenant and confirm in writing when it is "
                   "ready, including the named administrators and the applied Brand Assets."),
    ("num", "6.2", "byon has ten business days from that confirmation to test and to notify any "
                   "defect. Acceptance occurs on written confirmation, or on first productive use "
                   "with a customer, or on expiry of that period without notice of a defect."),
    ("num", "6.3", "Where byon notifies a defect within the test period, objectale will remedy it "
                   "and the test period restarts for the affected part."),

    ("h2", "7. Operation and responsibilities"),
    ("num", "7.1", "The platform is operated by the Vendor. byon does not host it and is not "
                   "responsible for its infrastructure."),
    ("num", "7.2", "byon is responsible for its Tenant's users, its own customer contracts, its "
                   "own first-line support and the accuracy of anything byon adds to a "
                   "deliverable."),
    ("num", "7.3", "objectale is responsible for second-line support to byon and for escalation to "
                   "the Vendor."),
    ("num", "7.4", "byon will not represent that objectale or the Vendor provides support "
                   "directly to byon's customers."),

    ("h2", "8. Data protection in a white-label deployment"),
    ("num", "8.1", "Branding does not change the roles under data protection law. The Data "
                   "Processing Agreement applies unchanged."),
    ("num", "8.2", "byon will make its own transparency information available to its customers. "
                   "byon may describe the processing chain in its own words provided the "
                   "description is accurate and names the sub-processors disclosed in the Data "
                   "Processing Agreement."),
    ("num", "8.3", "A customer of byon retains every right it has under the GDPR against byon as "
                   "controller. Branding does not remove or reduce it."),

    ("h2", "9. Service levels in a white-label deployment"),
    ("num", "9.1", "The Service Level Agreement applies to the branded service as it applies to "
                   "the unbranded service."),
    ("num", "9.2", "byon may offer its own customers a service level of its choosing. Where byon "
                   "commits to more than objectale owes byon, byon bears the difference."),
    ("num", "9.3", "Service credits under the Service Level Agreement are payable to byon and not "
                   "to byon's customers."),

    ("h2", "10. Commercial terms"),
    ("num", "10.1", "The white-label discount and any one-off charge are recorded in Schedule A."),
    ("num", "10.2", "A one-off charge, where agreed, covers tenant configuration, brand "
                    "application, validation of the rendered output and enablement of byon's "
                    "contacts. It is payable on acceptance under clause 6.2."),
    ("num", "10.3", "The white-label discount applies only while this OEM Agreement is in force. "
                    "If it ends, byon's discount reverts to the level in Schedule 2 of the "
                    "Framework Agreement from the next billing period."),

    ("h2", "11. Term, termination and exit"),
    ("num", "11.1", "This OEM Agreement runs for the term of the Framework Agreement unless "
                    "terminated earlier."),
    ("num", "11.2", "Either party may terminate this OEM Agreement on three months' written "
                    "notice, and for good cause under clause 19.2 of the Framework Agreement."),
    ("num", "11.3", "On termination byon will stop generating Branded Deliverables. Deliverables "
                    "already generated may continue to be used by the customers for whom they were "
                    "produced."),
    ("num", "11.4", "objectale will remove byon's Brand Assets from the platform within 30 days of "
                    "termination and will confirm removal in writing."),
    ("num", "11.5", "Where the parties agree a transition, byon may continue to serve existing "
                    "customers under clause 20.4 of the Framework Agreement, unbranded unless "
                    "objectale agrees otherwise in writing."),

    ("h2", "12. Governing law and jurisdiction"),
    ("num", "12.1", "Clause 24 of the Framework Agreement applies to this OEM Agreement: German "
                    "law, excluding the UN Convention on Contracts for the International Sale of "
                    "Goods, and the exclusive place of jurisdiction is Frankfurt am Main."),

    ("pagebreak",),
    ("h2", "Schedule A - White-label commercial terms"),
    ("table", ["Item", "Detail"], [
        ["White-label discount on list", "[__]%"],
        ["One-off set-up charge", "[EUR __ / none]"],
        ["Minimum commitment for the white-label discount", "[__ seats / __ runs per quarter]"],
        ["Attribution line", "[retained / removal agreed by the Vendor on __]"],
        ["Service name used by byon", "[ ]"],
        ["Tenant administrators", "[name] · [e-mail]"],
        ["Brand assets supplied", "[template .pptx] · [logo .png] · [colour palette]"],
        ["Target date for tenant readiness", "[ ]"],
    ]),
    ("note", "The attribution row is the one that needs an answer from the Vendor before it is "
             "filled in. Leaving it as \"retained\" is the safe default and is what the platform "
             "does today."),

    ("pagebreak",),
    ("h2", "Signatures"),
    ("sig", "For %s" % OBJECTALE["name"], "For %s" % BYON["name"],
     ["Name:", "Function:", "Place:", "Date:"]),
]

DE = [
    ("h1", "WHITE-LABEL-/OEM-VERTRAG"),
    ("meta", "%s und %s  ·  Ergänzung zum Wiederverkäufer-Rahmenvertrag  ·  Version %s  ·  %s"
     % (OBJECTALE["name"], BYON["name"], VERSION, DATE_DE)),
    ("p", "Dieser White-Label-/OEM-Vertrag (der \"OEM-Vertrag\") tritt am [Datum des "
          "Inkrafttretens des OEM-Vertrages] zwischen %s (\"objectale\") und %s (\"byon\") in "
          "Kraft." % (OBJECTALE["name"], BYON["name"])),
    ("note", NOTE_DE),

    ("h2", "1. Verhältnis zum Wiederverkäufer-Rahmenvertrag"),
    ("num", "1.1", "Dieser OEM-Vertrag ergänzt den zwischen den Parteien geschlossenen "
                   "Wiederverkäufer-Rahmenvertrag vom [Datum des Rahmenvertrages] (der "
                   "\"Rahmenvertrag\") und ist dessen Bestandteil."),
    ("num", "1.2", "Im Rahmenvertrag definierte Begriffe haben hier dieselbe Bedeutung, sofern "
                   "Ziffer 2 nichts anderes bestimmt."),
    ("num", "1.3", "Bei Widersprüchen zwischen diesem OEM-Vertrag und dem Rahmenvertrag geht "
                   "dieser OEM-Vertrag ausschließlich für White-Label-Fragen vor."),
    ("num", "1.4", "Ziffer 15 (Vertraulichkeit), Ziffer 17 (Haftung), Ziffer 24 (Anwendbares Recht "
                   "und Gerichtsstand) und der Auftragsverarbeitungsvertrag bleiben unberührt."),
    ("num", "1.5", "Dieser OEM-Vertrag endet automatisch mit dem Rahmenvertrag."),

    ("h2", "2. Begriffsbestimmungen"),
    ("num", "2.1", "\"Gebrandetes Ergebnisdokument\" ist eine von der Plattform erzeugte "
                   "Präsentation, ein Bericht oder ein Laufprotokoll, das nach Ziffer 3 die Marke "
                   "von byon trägt."),
    ("num", "2.2", "\"Markenmaterial\" sind die von byon hierfür bereitgestellte Vorlage, das "
                   "Logo, die Farbpalette und die Schriftarten."),
    ("num", "2.3", "\"Herkunftshinweis\" ist die einzelne Zeile auf der Titelseite jedes "
                   "Ergebnisdokuments, die die Plattform benennt."),
    ("num", "2.4", "\"Mandant\" ist das gesondert konfigurierte Konto von byon auf der Plattform."),

    ("h2", "3. Einräumung der White-Label-Rechte"),
    ("num", "3.1", "objectale räumt byon für die Laufzeit und im Gebiet das nicht ausschließliche, "
                   "nicht übertragbare Recht ein, die Plattform und ihre Ergebnisdokumente unter "
                   "der eigenen Marke von byon anzubieten."),
    ("num", "3.2", "byon darf sein Markenmaterial so anwenden, dass jede erzeugte Präsentation und "
                   "jeder Bericht die Farben, Schriften und das Logo von byon trägt. byon wendet "
                   "es selbst über die White-Label-Funktion der Plattform durch Hochladen einer "
                   "eigenen Vorlage an; objectale muss an jeder Änderung nicht beteiligt werden."),
    ("num", "3.3", "byon darf den Dienst in der eigenen Preisliste und im eigenen Marketing unter "
                   "einer von byon gewählten Bezeichnung führen, sofern diese Bezeichnung dem "
                   "Namen der Plattform oder einer Kennzeichnung des Herstellers nicht "
                   "verwechslungsfähig ähnlich ist."),
    ("num", "3.4", "byon darf sich seinen Kunden gegenüber als Vertragspartner und Erbringer des "
                   "gebrandeten Dienstes darstellen."),
    ("num", "3.5", "Das Recht umfasst nicht den Quellcode, nicht das Recht, die Plattform auf "
                   "eigener Infrastruktur zu betreiben, und nicht das Recht, die Assessment-Engine "
                   "zu verändern."),

    ("h2", "4. Grenzen aus der Rechtekette"),
    ("p", "Diese Klausel benennt ausdrücklich, was objectale nicht einräumen kann, damit byon es "
          "einem Kunden nicht zusagt."),
    ("num", "4.1", "Der Herkunftshinweis wird durch den Distributionsvertrag zwischen objectale und dem "
                   "Hersteller bestimmt. Sofern Anlage A nicht festhält, dass der Hersteller der "
                   "Entfernung für byon zugestimmt hat, trägt jedes Ergebnisdokument eine kleine "
                   "Herkunftszeile; byon wird sie nicht entfernen, verdecken oder verändern."),
    ("num", "4.2", "Schweregradfarben und sonstige Elemente, die die Plattform als bedeutungstragend "
                   "für den Leser und nicht als Markenmerkmal behandelt, werden von der "
                   "White-Label-Funktion nicht umgefärbt; byon wird nicht versuchen, sie zu "
                   "verändern."),
    ("num", "4.3", "objectale wird den Hersteller auf schriftliche Anfrage von byon fragen, ob ein "
                   "weitergehendes White-Label-Recht eingeräumt werden kann, und byon die Antwort "
                   "mitteilen. objectale sagt nicht zu, dass die Antwort positiv ausfällt."),
    ("num", "4.4", "Entzieht oder beschränkt der Hersteller ein White-Label-Recht, informiert "
                   "objectale byon unverzüglich; die Parteien stimmen nach Treu und Glauben ab, wie "
                   "mit bestehenden Kundenzusagen von byon umzugehen ist."),

    ("h2", "5. Markenmaterial und Qualität"),
    ("num", "5.1", "byon räumt objectale und dem Hersteller ein Nutzungsrecht am Markenmaterial "
                   "ausschließlich zur Erzeugung gebrandeter Ergebnisdokumente für byon ein. Das "
                   "Recht endet mit diesem OEM-Vertrag."),
    ("num", "5.2", "byon sichert zu, die Rechte am Markenmaterial zu halten und dass dessen Nutzung "
                   "nach diesem OEM-Vertrag keine Rechte Dritter verletzt, und stellt objectale von "
                   "entgegenstehenden Ansprüchen frei."),
    ("num", "5.3", "byon ist dafür verantwortlich, das erzeugte Ergebnis vor dem Versand an einen "
                   "Kunden zu prüfen. Die Plattform zeigt byon vor dem Speichern einer Marke eine "
                   "gerenderte Titel- und Inhaltsseite; byon wird diesen Schritt nutzen."),
    ("num", "5.4", "byon wird ein gebrandetes Ergebnisdokument nicht so darstellen, als sei das "
                   "Assessment von einer Zertifizierungsstelle, einem Abschlussprüfer oder einer "
                   "Aufsichtsbehörde erstellt worden."),

    ("h2", "6. Einrichtung des Mandanten und Abnahme"),
    ("num", "6.1", "objectale richtet den Mandanten von byon ein und bestätigt schriftlich dessen "
                   "Bereitstellung, einschließlich der benannten Administratoren und des "
                   "angewendeten Markenmaterials."),
    ("num", "6.2", "byon hat ab dieser Bestätigung zehn Arbeitstage Zeit, zu testen und Mängel "
                   "anzuzeigen. Die Abnahme erfolgt mit schriftlicher Bestätigung, mit der ersten "
                   "produktiven Nutzung bei einem Kunden oder mit Ablauf dieser Frist ohne "
                   "Mängelanzeige."),
    ("num", "6.3", "Zeigt byon innerhalb der Testfrist einen Mangel an, beseitigt objectale ihn und "
                   "die Testfrist beginnt für den betroffenen Teil erneut."),

    ("h2", "7. Betrieb und Verantwortlichkeiten"),
    ("num", "7.1", "Die Plattform wird vom Hersteller betrieben. byon hostet sie nicht und ist für "
                   "ihre Infrastruktur nicht verantwortlich."),
    ("num", "7.2", "byon ist verantwortlich für die Nutzer des eigenen Mandanten, die eigenen "
                   "Kundenverträge, den eigenen First-Level-Support und die Richtigkeit dessen, was "
                   "byon einem Ergebnisdokument hinzufügt."),
    ("num", "7.3", "objectale ist verantwortlich für den Second-Level-Support gegenüber byon und "
                   "für die Eskalation an den Hersteller."),
    ("num", "7.4", "byon wird nicht darstellen, dass objectale oder der Hersteller unmittelbar "
                   "Support für Kunden von byon leistet."),

    ("h2", "8. Datenschutz im White-Label-Betrieb"),
    ("num", "8.1", "Das Branding ändert die datenschutzrechtlichen Rollen nicht. Der "
                   "Auftragsverarbeitungsvertrag gilt unverändert."),
    ("num", "8.2", "byon stellt seinen Kunden eigene Transparenzinformationen zur Verfügung. byon "
                   "darf die Verarbeitungskette mit eigenen Worten beschreiben, sofern die "
                   "Beschreibung zutreffend ist und die im Auftragsverarbeitungsvertrag offengelegten "
                   "Unterauftragsverarbeiter benennt."),
    ("num", "8.3", "Einem Kunden von byon bleiben sämtliche Rechte nach der DSGVO gegenüber byon "
                   "als Verantwortlichem erhalten. Das Branding beseitigt oder verkürzt sie nicht."),

    ("h2", "9. Service Levels im White-Label-Betrieb"),
    ("num", "9.1", "Das Service Level Agreement gilt für den gebrandeten Dienst wie für den "
                   "ungebrandeten."),
    ("num", "9.2", "byon darf seinen Kunden ein Service Level eigener Wahl anbieten. Sagt byon mehr "
                   "zu, als objectale byon schuldet, trägt byon die Differenz."),
    ("num", "9.3", "Service-Gutschriften nach dem Service Level Agreement stehen byon und nicht den "
                   "Kunden von byon zu."),

    ("h2", "10. Kommerzielle Bedingungen"),
    ("num", "10.1", "Der White-Label-Rabatt und ein etwaiges einmaliges Entgelt sind in Anlage A "
                    "festgehalten."),
    ("num", "10.2", "Ein vereinbartes einmaliges Entgelt deckt die Einrichtung des Mandanten, die "
                    "Anwendung der Marke, die Prüfung des erzeugten Ergebnisses und die Befähigung "
                    "der Ansprechpartner von byon. Es ist mit der Abnahme nach Ziffer 6.2 fällig."),
    ("num", "10.3", "Der White-Label-Rabatt gilt nur, solange dieser OEM-Vertrag in Kraft ist. "
                    "Endet er, gilt ab der nächsten Abrechnungsperiode wieder der Rabatt nach "
                    "Anlage 2 des Rahmenvertrages."),

    ("h2", "11. Laufzeit, Beendigung und Übergang"),
    ("num", "11.1", "Dieser OEM-Vertrag läuft für die Laufzeit des Rahmenvertrages, sofern er nicht "
                    "vorher beendet wird."),
    ("num", "11.2", "Jede Partei kann diesen OEM-Vertrag mit einer Frist von drei Monaten "
                    "schriftlich sowie aus wichtigem Grund nach Ziffer 19.2 des Rahmenvertrages "
                    "kündigen."),
    ("num", "11.3", "Mit Beendigung stellt byon die Erzeugung gebrandeter Ergebnisdokumente ein. "
                    "Bereits erzeugte Ergebnisdokumente dürfen von den Kunden, für die sie erstellt "
                    "wurden, weiter genutzt werden."),
    ("num", "11.4", "objectale entfernt das Markenmaterial von byon binnen 30 Tagen nach Beendigung "
                    "von der Plattform und bestätigt die Entfernung schriftlich."),
    ("num", "11.5", "Vereinbaren die Parteien einen Übergang, darf byon bestehende Kunden nach "
                    "Ziffer 20.4 des Rahmenvertrages weiter betreuen, und zwar ungebrandet, sofern "
                    "objectale nichts anderes schriftlich zustimmt."),

    ("h2", "12. Anwendbares Recht und Gerichtsstand"),
    ("num", "12.1", "Für diesen OEM-Vertrag gilt Ziffer 24 des Rahmenvertrages: deutsches Recht "
                    "unter Ausschluss des UN-Kaufrechts, ausschließlicher Gerichtsstand ist "
                    "Frankfurt am Main."),

    ("pagebreak",),
    ("h2", "Anlage A - Kommerzielle White-Label-Bedingungen"),
    ("table", ["Angabe", "Detail"], [
        ["White-Label-Rabatt auf Liste", "[__]%"],
        ["Einmaliges Einrichtungsentgelt", "[EUR __ / keines]"],
        ["Mindestabnahme für den White-Label-Rabatt", "[__ Seats / __ Läufe je Quartal]"],
        ["Herkunftshinweis", "[bleibt bestehen / Entfernung vom Hersteller zugestimmt am __]"],
        ["Von byon verwendete Dienstbezeichnung", "[ ]"],
        ["Administratoren des Mandanten", "[Name] · [E-Mail]"],
        ["Bereitgestelltes Markenmaterial", "[Vorlage .pptx] · [Logo .png] · [Farbpalette]"],
        ["Zieltermin für die Bereitstellung des Mandanten", "[ ]"],
    ]),
    ("note", "Die Zeile zum Herkunftshinweis ist diejenige, die vor dem Ausfüllen eine Antwort des "
             "Herstellers benötigt. \"Bleibt bestehen\" ist die sichere Voreinstellung und "
             "entspricht dem heutigen Verhalten der Plattform."),

    ("pagebreak",),
    ("h2", "Unterschriften"),
    ("sig", "Für %s" % OBJECTALE["name"], "Für %s" % BYON["name"],
     ["Name:", "Funktion:", "Ort:", "Datum:"]),
]
