#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build Cybergod_Attack_Footprint.html - a 3D, scroll-driven record of what actually hit
cybergod.ai, in the visual language of the GEOPOL animated deliverable.

    python marketing/build_attack_globe.py

WHY three.js AND NOT UNITY (the operator asked; this is the answer, with numbers).
  Unity WebGL export is 20-50 MB across a .wasm, a .data, a .framework.js and a loader, it needs
  a build pipeline and a web server, and it CANNOT be a single file you attach to an email or
  drop on a partner's laptop. Time-to-first-frame is seconds.
  three.js r128 from cdnjs is ~600 KB behind one <script> tag, the page stays ONE self-contained
  .html, and it is already the pattern this repo uses in build_report_html.js. Everything the
  operator asked for - real 3D, depth, motion, glow - is native to it.
  OrbitControls is deliberately NOT loaded: it is a separate file at a path that moves between
  releases, and a second CDN dependency is a second thing that can 404 in front of a customer.
  The drag/inertia camera here is ~30 lines and cannot break.
  A WebGL failure falls back to a 2D canvas rather than a blank rectangle.

HONESTY RULES BAKED INTO THIS FILE, because it is a security artifact about our own logs:
  1. The 604 were DETECTED over the period the log covers. They were not "stopped": the shield
     shipped afterwards. Every string in here says detected.
  2. Only FIVE sources are geolocated in our data. The other ~600 render as unlabelled traffic
     and the page says so on screen. Inventing a country heat map would be precisely the failure
     the assessment engine refuses to make in a customer deck.
  3. Every number is traceable to `python analyse_attacks.py` over colt-web's event log, or to
     the operator's own Telegram alerts. Sources are printed in the footer.
"""
import base64
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "Cybergod_Attack_Footprint.html")

# ---------------------------------------------------------------------------------------------
# THE DATA. Measured, not estimated. analyse_attacks.py over colt-web's event log, 10-11 Aug 2026.
# ---------------------------------------------------------------------------------------------
TOTALS = {"requests": 156511, "sources": 2253, "scanners": 604,
          "classes_before": 29, "classes_after": 48, "gaps_closed": 19}

# Attack classes by DISTINCT SOURCE COUNT, with a real example path for each.
CLASSES = [
    ("wordpress",   483, "#FF3B57", "/wp-login.php"),
    ("php_probe",   481, "#FF7A33", "/alfa.php"),
    ("admin_panel", 162, "#FFC33C", "/administrator/"),
    ("shell_rce",   113, "#FF3B57", "/cgi-bin/.%2e/bin/sh"),
    ("template",    100, "#9E86FF", "/[workspace]/"),
    ("env_secrets",  96, "#FF3B57", "/.env"),
    ("backup_file",  45, "#37C8FF", "/backup.sql"),
    ("api_docs",     28, "#37C8FF", "/swagger.json"),
    ("iot_router",    6, "#FFC33C", "/HNAP1/"),
    ("traversal",     6, "#FF7A33", "/../../etc/passwd"),
    ("docs_leak",     3, "#9E86FF", "/DOCS.md"),
]

ALERTS = [("path_probe", 212), ("dir_bruteforce", 208), ("authz_probe", 85), ("ip_burst", 71)]

# THE ONLY GEOLOCATED SOURCES WE HAVE. Everything else is deliberately unlabelled.
# lat, lon, label, detail, colour, kind
KNOWN = [
    (42.51,   1.52, "AD", "195.178.110.199",
     "6 browser fingerprints in 2 seconds", "#FF3B57", "scanner"),
    (46.60,   2.35, "FR", "Next.js fingerprinting cluster",
     "days of probing a framework we do not run", "#FF7A33", "scanner"),
    (-1.29,  36.82, "KE", "136.67.108.237",
     "probe_path -> tarpit -> 15 min block", "#FFC33C", "scanner"),
    (51.16,  10.45, "DE", "212.58.119.138",
     "439 x 404 - a REAL visitor", "#26D98A", "human"),
    (31.05,  34.85, "IL", "46.116.177.24",
     "362 x 404 - a REAL visitor", "#26D98A", "human"),
]
TARGET = (50.11, 8.68, "FRA1 - Frankfurt", "cybergod.ai / 64.225.108.200")

MODELS = [("deepseek-3.2", "soldier"), ("llama-4-maverick", "soldier"),
          ("gemma-4-31B-it", "auditor"), ("kimi-k2.6", "auditor")]

# The Andorra incident, verbatim from the alerts.
ANDORRA_UAS = ["Safari / macOS", "Chrome / Linux", "Chrome / macOS",
               "Edge / Windows", "Firefox / Windows", "Firefox / macOS"]
ANDORRA_PATHS = ["/", "//slug", "/DOCS.md", "/IAM.md", "/[workspace]/"]

TAPE = ["/wp-login.php", "/.env", "/.git/config", "/administrator/", "/alfa.php",
        "/lock360.php", "/this_is_a_new_hello_world.php", "/.aws/credentials",
        "/swagger.json", "/HNAP1/", "/backup.sql", "/DOCS.md", "/IAM.md",
        "/[workspace]/", "/.svn/wc.db", "/.vite/manifest.json", "/api/graphql",
        "/wp-content/plugins/", "/vendor/phpunit/", "/.ssh/id_rsa"]


def land_mask_b64():
    """The dotted continents. Generated by _landmask.py and embedded, so the page makes no
    network call for geography - a customer opening this on a plane still sees a globe."""
    p = os.path.join(HERE, "_landmask.b64")
    if os.path.exists(p):
        return open(p).read().strip()
    png = os.path.join(HERE, "_landmask.png")
    if os.path.exists(png):
        return base64.b64encode(open(png, "rb").read()).decode()
    sys.exit("missing _landmask.b64 - run marketing/_landmask.py first")


def build():
    from attack_globe_page import PAGE          # noqa: E402  (kept beside this file)
    html = PAGE.replace("__MASK__", land_mask_b64())
    for key, val in (("__TOTALS__", TOTALS), ("__CLASSES__", CLASSES), ("__KNOWN__", KNOWN),
                     ("__TARGET__", TARGET), ("__MODELS__", MODELS), ("__ALERTS__", ALERTS),
                     ("__UAS__", ANDORRA_UAS), ("__APATHS__", ANDORRA_PATHS), ("__TAPE__", TAPE)):
        import json
        html = html.replace(key, json.dumps(val))
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(html)
    return OUT


if __name__ == "__main__":
    p = build()
    print("wrote %s (%.1f KB)" % (p, os.path.getsize(p) / 1024.0))
