#!/usr/bin/env python3
"""make_icons.py — regenerate every app icon from one definition.

    cd webapp/frontend && python tools/make_icons.py

WHY IT IS A SCRIPT AND NOT A ONE-OFF: the home-screen tile is the most visible brand asset there
is, and it lives in SEVEN files (two SVG sources plus five PNGs that Android and iOS actually
install). When the site was rebranded, the CSS was changed and these were not, so the installed app
kept the previous company's dark teal months afterwards. A single definition, regenerated by one
command, is the only way that does not happen again. tools/contrast_gate.mjs asserts the sources
carry no retired brand colour.

Needs cairosvg and pillow: pip install cairosvg pillow
"""
import cairosvg, io
from PIL import Image

GRAD = ('<defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1">'
        '<stop offset="0" stop-color="#4F46E5"/><stop offset=".55" stop-color="#7C3AED"/>'
        '<stop offset="1" stop-color="#C026D3"/></linearGradient></defs>')

# rounded tile, used for the browser/desktop icon
ICON = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">' + GRAD +
        '<rect width="512" height="512" rx="96" fill="url(#g)"/>'
        '<path d="M188 140 L286 256 L188 372" fill="none" stroke="#22D3EE" stroke-width="46" '
        'stroke-linecap="round" stroke-linejoin="round"/>'
        '<circle cx="352" cy="256" r="26" fill="#22D3EE"/></svg>')

# MASKABLE: Android crops to a squircle, so the artwork must sit inside the safe zone (the middle
# 80%) and the background must bleed to every edge. Hence no rounded corners and a smaller glyph.
MASK = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">' + GRAD +
        '<rect width="512" height="512" fill="url(#g)"/>'
        '<path d="M205 165 L281 256 L205 347" fill="none" stroke="#22D3EE" stroke-width="38" '
        'stroke-linecap="round" stroke-linejoin="round"/>'
        '<circle cx="333" cy="256" r="21" fill="#22D3EE"/></svg>')

open("icon.svg", "w").write(ICON)
open("icon-maskable.svg", "w").write(MASK)

def png(svg, path, size, opaque=False):
    data = cairosvg.svg2png(bytestring=svg.encode(), output_width=size, output_height=size)
    im = Image.open(io.BytesIO(data)).convert("RGBA")
    if opaque:
        # iOS composites any alpha to BLACK, so the apple-touch icons must be flattened. Recorded
        # in CLAUDE.md the first time round; regenerating them is exactly when it gets forgotten.
        bg = Image.new("RGBA", im.size, (79, 70, 229, 255))
        im = Image.alpha_composite(bg, im).convert("RGB")
    im.save(path)
    return path, size, ("opaque" if opaque else "alpha")

out = [png(ICON, "icon-192.png", 192), png(ICON, "icon-512.png", 512),
       png(MASK, "icon-maskable-192.png", 192), png(MASK, "icon-maskable-512.png", 512),
       png(ICON, "apple-touch-icon.png", 180, True), png(ICON, "apple-touch-icon-167.png", 167, True),
       png(ICON, "apple-touch-icon-152.png", 152, True)]
for p, s, m in out: print("  %-28s %dx%d %s" % (p, s, s, m))
